### ISSUE TITLE
Hom alt GT reported incorrectly

### ISSUE THREAD

**Issue by bredeson** [Illumina/strelka#74] opened 2018-11-08 23:38 UTC
Hey Strelka Devs!

I saw the Strelka2 communication paper in Nature Methods and wanted to give it a try on my data set. I am really excited about Strelka's performance over GATK and FreeBayes. While examining the output of a Strelka run, however, I noticed that many homozygous gentoypes for the alternate allele are being reported incorrectly as `1` instead of `1/1` in my diploid organism. Is this intended?

```
> zcat variants.pass.vcf.gz | grep -v '^#' | perl -ane 'print if $F[9] =~ /^1:/' | head
Contig0|arrow|arrow	536183	.	C	G	126	PASS	MQ=55;SNVHPOL=5	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:0,7:0,5:0,2:8:3:99:9:160,0:-14.5
Contig0|arrow|arrow	737197	.	G	C	42	PASS	MQ=51;SNVHPOL=3	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:0,20:0,7:0,13:20:40:99:6:327,0:-28.2
Contig0|arrow|arrow	920813	.	G	C	73	PASS	MQ=40;SNVHPOL=8	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:1,9:0,0:1,9:10:24:99:6:107,0:0.0
Contig0|arrow|arrow	1100429	.	T	C	549	PASS	MQ=56;SNVHPOL=2	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:0,160:0,34:0,126:160:411:99:6:370,0:-99.0
Contig0|arrow|arrow	1299877	.	G	T	130	PASS	MQ=56;SNVHPOL=4	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:0,8:0,4:0,4:8:113:99:6:165,0:-18.0
Contig0|arrow|arrow	1521280	.	C	G	90	PASS	MQ=60;SNVHPOL=4	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:1,7:1,5:0,2:8:6:99:30:125,0:-13.8
Contig0|arrow|arrow	1848451	.	G	T	93	PASS	MQ=40;SNVHPOL=6	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:6,20:3,5:3,15:26:26:99:6:128,0:2.3
Contig0|arrow|arrow	2801865	.	G	T	15	PASS	MQ=37;SNVHPOL=7	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:1,4:0,0:1,4:5:12:44:5:49,0:0.0
Contig0|arrow|arrow	8222320	.	C	G	47	PASS	MQ=30;SNVHPOL=8	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:0,6:0,2:0,4:7:21:99:4:144,0:-13.8
Contig0|arrow|arrow	11377020	.	A	G	232	PASS	MQ=39;SNVHPOL=6	GT:AD:ADF:ADR:DP:DPF:GQ:GQX:PL:SB	1:0,20:0,20:0,0:25:251:99:4:267,0:0.0
```

I'm using Strelka v2.9.4-0-g0b1a133 and I called variants using the `configureStrelkaGermlineWorkflow.py` script on a GNU/Linux x86_64 machine with 64 cores and 512GB of memory.

**Comment by sangtaekim** [comment] 2018-11-09 16:59
Hi Jessen,

This is likely to be due to spanning deletions (chr1:66160 in the example below), e.g.
```
chr1    66160   .       TTATATA T       75      PASS    CIGAR=1M6D;RU=TA;REFREP=7;IDREP=4;MQ=44;EVSF=0,4,2,0.9756
3,0.28249,44.073,0.61538,0.6,63,4,18,1,1.3333,-9.4117,7,0.125,0.8125,5.7692,4.8462,4.8462,0.4,75,63    GT:GQ:GQX:
DPI:AD:ADF:ADR:FT:PL  0/1:63:63:13:4,6:0,2:4,4:PASS:87,0,60
chr1    66161   .       T       .       .       PASS    .       GT:GQX:DP:DPF:MIN_DP    0:63:4:0:4
chr1    66162   .       A       T       63      PASS    SNVHPOL=5;MQ=43;EVSF=1,42.77,5,0,-0.5,0,0.26923,0.57143,63,0.66667,0,69.078,69.078,64.5,36,0.28571,15.75,15.75,22.75,0,63,91,1  GT:GQ:GQX:DP:DPF:AD:ADF:ADR:SB:FT:PL    1:91:63:4:0:0,4:0,0:0,4:0.0:PASS:97,0
chr1    66163   .       T       .       .       PASS    END=66166;BLOCKAVG_min30p3a     GT:GQX:DP:DPF:MIN_DP    0:63:4:0:4
```

This link (https://sites.google.com/site/gvcftools/home/faq#TOC-Why-are-records-reported-in-the-gVCF-inside-of-homozygous-and-heterozygous-indels-) explains why we chose this format.

**Comment by bredeson** [comment] 2018-11-09 18:32
Hey @sangtaekim,

Thank you for the prompt reply. I read the discussion at the link you provided, and the rationale for splitting complex variants into individual variant records makes complete sense to me; however, could you elaborate on why reporting genotypes as haploid (`GT=1`) is preferred over, say, reporting diploid genotypes with a hemizygous state (*i.e.*, with a "missing" allele: `GT=./1`)?  

An argument in favor of diploid genotypes with a missing allele is that the ploidy of the locus has not truly changed (if we consider the deletion an allele, then the two alleles at the locus still segregate in a diploid manner), but the hemizygosity of the linked variant in the deletion is evident by the missingness of an allele in the genotype. The alleles that are called at these genotypes may also then be explicitly phased with respect to the reference allele at the deletion locus and the surrounding diploid variants on the same haplotype using the VCF spec's standard phased genotype notation (`1|.` or `.|1`). A haploid genotype disallows explicit phasing, making tracking the phase (and which alleles it is linked to in the surrounding diploid genome) a programatic juggling exercise. 

Thank you for hearing my thoughts on this. 

- Jessen

**Comment by ctsa** [comment] 2018-11-09 23:57
@bredeson  -  Thanks for your feedback. `./1` is another popular workaround to represent hemizygous variants, but this is also problematic -- does this imply (a) ambiguity between `0/1` and `1/1` (b) (as intended in this case), the '.' refers to a specific third allele that we can't easily enumerate or (c) the '.' represents any possible second allele?

I would agree that while they're both problematic, the `./1` representation tends to come out slightly ahead. Given that new mechanisms are being included in the spec to more correctly communicate these types the best path ahead will likely be moving to VCF 4.2/4.3 and taking advantage of '*' alleles.

**Closed as completed** 2019-02-07 00:18 UTC
