### ISSUE TITLE
No indels found using strelka2

### ISSUE THREAD

**Issue by ysbioinfo** [Illumina/strelka#76] opened 2018-11-17 12:46 UTC
Hi
I want to use Strelka to call somatic indels on my data(WES, HCC). I've used Strelka many times before, it works well. But this time the results seems strange. Although the number of SNVs given by Strelka is in a reasonable range, but almost no indels are found in any sample(two samples with 1 indel and others with 0 indel), even in hypermutated sample whose somatic SNVs are more than 3000. I see the candidate indels in somatic.indels.vcf.gz, first, the total number of candidates is verysmall(~200-500), and most of them are filtered because REF_QSI.
I've tried other softwares such as Mutect2, Lancet, they give a reasonable number of indels, but I still want to use Strelka because I'm familiar with it. So I wonder if you have any insight in why no indels can be detected by Strelka. Could you give me some advice?
(Duplicates are removed from BAM files. GATK Indelrealigner and Baserecalibrator are applied on BAM files. MANTA has been run before Strelka to call the candidate indels).

Thanks 
Yang

**Comment by sangtaekim** [comment] 2018-11-19 17:53
Hi Yang,

Thanks for the report. Can you send us the data for us to reproduce the issue (preferably bamlets/reference including the regions that Strelka missed variants called by others)?

**Comment by ysbioinfo** [comment] 2018-11-20 12:40
[bam_indel.zip](https://github.com/Illumina/strelka/files/2599703/bam_indel.zip)
Hi kim,
Thanks for your reply! I only uploaded 6 bam files (3 tumor-normal pairs) due to the 10M size limit of Github. I used samtools view to extract all reads within [pos -10bp, pos +10bp] (pos is the genome position of a indel called by Lancet) and output them in the sample.indel.bam. The reference genome is hg19. Is this enough for your reproducing?
Yang

**Comment by sangtaekim** [comment] 2018-11-20 17:18
Thanks @snoopy-448 . Can you also send me a list of indels that must be called?

Sangtae

**Comment by sangtaekim** [comment] 2018-11-20 17:28
What is the Strelka version that you used? Can you also send me the Strelka configuration command (e,g, configureStrelkaSomaticWorkflow.py --normalBam normal.bam --tumorBam tumor.bam ...)?

**Comment by ysbioinfo** [comment] 2018-11-21 03:43
Sangtae,
The Strelka version I used is 2.7.1 and my configuration command is:
```
configureStrelkaSomaticWorkflow.py \
 --normalBam P01N.bam\
 --tumorBam P01T.bam\
 --referenceFasta hg19.fa\
 --indelCandidates candidateSmallIndels.vcf.gz\
 --runDir outdir
```
So sorry that I don't have a list of indels that "must be called" from my data : ( . I don't know which indel should be there. It's possible that there is no indel in my WES data, but with extremely low probability, because the sample collection and sequencing method, the cancer type and the pipeline we used for generating bam files are same as before. In addition, from my personal experience and the result of other papers, the number of indels in a HCC sample always range from 10~150 if it's not hypermutated. So I think it's strange that there is only 0-1 indel in all samples (n = 54).
I uploaded the indel list called by Lancet, will this be helpful for you? Many thanks.

Yang
[P03T.indel.txt](https://github.com/Illumina/strelka/files/2602555/P03T.indel.txt)
[P01T.indel.txt](https://github.com/Illumina/strelka/files/2602556/P01T.indel.txt)
[P02T.indel.txt](https://github.com/Illumina/strelka/files/2602557/P02T.indel.txt)

**Comment by sangtaekim** [comment] 2018-11-21 23:14
Thanks. I have several comments.

- Strelka 2.7.1 was released ~2 years ago and there have been lots of changes since then. I recommend to use the latest version (v2.9.10).
- For exome, it's important to add "--exome" (https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/README.md#exometargeted).
- It looks like the alt allele frequency is quite low for most indels. For such low AF indels, the default Strelka threshold is likely to be too stringent. I recommend to look at different SomaticEVS thresholds. For convenience, we provide a script for changing the thresholds: https://github.com/Illumina/strelka/blob/v2.9.x/scratch/util/reFilterSomaticVcf.py
- It is not necessary to run GATK IndelRealigner or BQSR before running Strelka. Strelka runs realignment and base quality adjustment internally.

Best,

Sangtae

**Comment by ysbioinfo** [comment] 2018-12-01 06:40
Many thanks! the latest version solved my problem.
Yang

**Comment by sangtaekim** [comment] 2018-12-03 19:13
Glad to hear that. I'm closing the ticket.

**Closed as completed by sangtaekim** 2018-12-03 19:13 UTC
