### ISSUE TITLE
Problem with long insertions in realigned RNASeq BAM files

### ISSUE THREAD

**Issue by mozack** [Illumina/strelka#70] opened 2018-09-24 15:46 UTC
Hi,

I have some test data that contains long insertions in RNA reads.   We are testing Strelka2 running against BAM files output by STAR and then realigned to reveal indels in the alignments.  There are several cases where a long insert is not mapped properly in the original alignments and Strelka2 is able to call them accurately.  In some of these same cases, when we input a realigned BAM containing accurately mapped reads into Strelka2, the variant is not called.  Could this be a problem with active region identification?  Are there parameters that can be used to tweak the active region window size?

You can get a feel for it in the attached screenshot.  Strelka2 makes the call with the BAM file represented in the top panel, but not for the one in the bottom panel.

![strelka2_long_insert](https://user-images.githubusercontent.com/1452590/45960943-63f4af80-bfeb-11e8-9f81-e07d05dcf6f0.png)

The expected call is:
```chr5    142602689       .       C       CCCGGTGGCAGGATGTATGGTCGGGCGAGCTCGGACATAGGTAGCCCTTGGTTGTTGTGACGGGATCACCTATTTGTGGAGGCGGTCCCCTATAATCGCG```

By comparison, GATK Haplotype Caller does make the correct call when run against the realigned BAM file.

We do see improved performance for Strelka2 calling against the realigned BAM file in other variant categories, so just using the original alignments would not be the preferred solution.

Please also see the attached zip file for for BAM snippets that can be used to reproduce the issue as well as scripts for execution
[strelka2_realigned_insert_issue.zip](https://github.com/Illumina/strelka/files/2411502/strelka2_realigned_insert_issue.zip)

Please note that maxIndelSize was set to 100 for this test run.

Thanks!

**Comment by sangtaekim** [comment] 2018-09-27 18:04
Thanks for reporting the issue. Can you also send us the reference fasta file for us to reproduce the issue? Your reference doesn't match with anything that we have. 

FYI, for indels of size > 49, we recommend to use Manta instead of Strelka and our tests don't cover calling them. There may be a glitch in handling large indels.

**Comment by mozack** [comment] 2018-09-27 18:46
Thanks for the response.  The reference fasta is available here:

``` https://webshare.bioinf.unc.edu/maven-repo/hg19.fa.gz ```

Please let me know if you have trouble downloading it.

We have tried Manta for DNA.  However, the Manta user guide appears to indicate that only fusions will be called when using the --rna flag.

**Comment by sangtaekim** [comment] 2018-09-27 20:49
Thanks, I could reproduce the issue. 

The long insertion is not called because Strelka ignores read alignments with edge indels (e.g. 40I60M) which is very rare (if any) in the data that we normally see. We don't plan to change this behavior. If you can somehow replace the edge insertions with soft clips, I expect Strelka would properly call the insertions.

**Comment by mozack** [comment] 2018-09-27 23:49
OK.  So, if one were to pass the Strelka2 realigned BAM back into the caller, these long insert calls would no longer be made then?

I will point out that other variant callers do benefit from the more accurate alignments.  Going back to the GATK HaplotypeCaller example, it does not call the insert in the original set of alignments, but it does in the more accurate alignments.  We see improved performance with other variant callers as well, so leaving the reads soft clipped when a more accurate alignment is available is not optimal. 

Would it be possible to provide an option to treat leading or trailing insertions as if they were soft clipped internally?

**Comment by sangtaekim** [comment] 2018-09-28 20:04
Strelka is optimized to call insertions far shorter than the read length (e.g. 49 or smaller). For short insertions, it would be fine to call them from realigned bam files even if there are "some" reads with edge insertions because other reads that fully span the insertion will trigger an active region. I forgot to mention it but the reads with edge indels are ignored only when creating active regions and determine candidate indels; they are still used when scoring indels. 

We want to keep the Strelka's command line interface as simple as possible and thus prefer not to provide the requested option. 

As an alternative, please consider making your own Strelka build so that it will not ignore reads with edge indels. You just need to comment out lines 100 and 141 ("if (! is_pinned_indel) return;") of https://github.com/Illumina/strelka/blob/v2.9.x/src/c%2B%2B/lib/starling_common/starling_pos_processor_indel_util.cpp and the unussed is_pinned_indel parameter since it's not used. I've just tested it and it could find the 99-base insertion.

Sorry for not providing a more convenient solution.

**Comment by mozack** [comment] 2018-10-01 13:05
OK.  Thanks for looking into it and thanks for the tip on the code change.

**Comment by sangtaekim** [comment] 2018-10-05 17:46
Thanks. Closing this ticket.

**Closed as completed by sangtaekim** 2018-10-05 17:46 UTC
